"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _OperationResult:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _OperationResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OperationResult.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Success: _OperationResult.ValueType  # 0
    PrepareTimeout: _OperationResult.ValueType  # 1
    CommitTimeout: _OperationResult.ValueType  # 2
    ForwardTimeout: _OperationResult.ValueType  # 3
    WrongExpectedVersion: _OperationResult.ValueType  # 4
    StreamDeleted: _OperationResult.ValueType  # 5
    InvalidTransaction: _OperationResult.ValueType  # 6
    AccessDenied: _OperationResult.ValueType  # 7
class OperationResult(_OperationResult, metaclass=_OperationResultEnumTypeWrapper):
    pass

Success: OperationResult.ValueType  # 0
PrepareTimeout: OperationResult.ValueType  # 1
CommitTimeout: OperationResult.ValueType  # 2
ForwardTimeout: OperationResult.ValueType  # 3
WrongExpectedVersion: OperationResult.ValueType  # 4
StreamDeleted: OperationResult.ValueType  # 5
InvalidTransaction: OperationResult.ValueType  # 6
AccessDenied: OperationResult.ValueType  # 7
global___OperationResult = OperationResult


class NewEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_ID_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    DATA_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    METADATA_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    event_id: builtins.bytes
    event_type: typing.Text
    data_content_type: builtins.int
    metadata_content_type: builtins.int
    data: builtins.bytes
    metadata: builtins.bytes
    def __init__(self,
        *,
        event_id: typing.Optional[builtins.bytes] = ...,
        event_type: typing.Optional[typing.Text] = ...,
        data_content_type: typing.Optional[builtins.int] = ...,
        metadata_content_type: typing.Optional[builtins.int] = ...,
        data: typing.Optional[builtins.bytes] = ...,
        metadata: typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","data_content_type",b"data_content_type","event_id",b"event_id","event_type",b"event_type","metadata",b"metadata","metadata_content_type",b"metadata_content_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","data_content_type",b"data_content_type","event_id",b"event_id","event_type",b"event_type","metadata",b"metadata","metadata_content_type",b"metadata_content_type"]) -> None: ...
global___NewEvent = NewEvent

class EventRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    EVENT_NUMBER_FIELD_NUMBER: builtins.int
    EVENT_ID_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    DATA_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    METADATA_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    CREATED_EPOCH_FIELD_NUMBER: builtins.int
    event_stream_id: typing.Text
    event_number: builtins.int
    event_id: builtins.bytes
    event_type: typing.Text
    data_content_type: builtins.int
    metadata_content_type: builtins.int
    data: builtins.bytes
    metadata: builtins.bytes
    created: builtins.int
    created_epoch: builtins.int
    def __init__(self,
        *,
        event_stream_id: typing.Optional[typing.Text] = ...,
        event_number: typing.Optional[builtins.int] = ...,
        event_id: typing.Optional[builtins.bytes] = ...,
        event_type: typing.Optional[typing.Text] = ...,
        data_content_type: typing.Optional[builtins.int] = ...,
        metadata_content_type: typing.Optional[builtins.int] = ...,
        data: typing.Optional[builtins.bytes] = ...,
        metadata: typing.Optional[builtins.bytes] = ...,
        created: typing.Optional[builtins.int] = ...,
        created_epoch: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created",b"created","created_epoch",b"created_epoch","data",b"data","data_content_type",b"data_content_type","event_id",b"event_id","event_number",b"event_number","event_stream_id",b"event_stream_id","event_type",b"event_type","metadata",b"metadata","metadata_content_type",b"metadata_content_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created",b"created","created_epoch",b"created_epoch","data",b"data","data_content_type",b"data_content_type","event_id",b"event_id","event_number",b"event_number","event_stream_id",b"event_stream_id","event_type",b"event_type","metadata",b"metadata","metadata_content_type",b"metadata_content_type"]) -> None: ...
global___EventRecord = EventRecord

class ResolvedIndexedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_FIELD_NUMBER: builtins.int
    LINK_FIELD_NUMBER: builtins.int
    @property
    def event(self) -> global___EventRecord: ...
    @property
    def link(self) -> global___EventRecord: ...
    def __init__(self,
        *,
        event: typing.Optional[global___EventRecord] = ...,
        link: typing.Optional[global___EventRecord] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event",b"event","link",b"link"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event",b"event","link",b"link"]) -> None: ...
global___ResolvedIndexedEvent = ResolvedIndexedEvent

class ResolvedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_FIELD_NUMBER: builtins.int
    LINK_FIELD_NUMBER: builtins.int
    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    @property
    def event(self) -> global___EventRecord: ...
    @property
    def link(self) -> global___EventRecord: ...
    commit_position: builtins.int
    prepare_position: builtins.int
    def __init__(self,
        *,
        event: typing.Optional[global___EventRecord] = ...,
        link: typing.Optional[global___EventRecord] = ...,
        commit_position: typing.Optional[builtins.int] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","event",b"event","link",b"link","prepare_position",b"prepare_position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","event",b"event","link",b"link","prepare_position",b"prepare_position"]) -> None: ...
global___ResolvedEvent = ResolvedEvent

class WriteEvents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    EXPECTED_VERSION_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    event_stream_id: typing.Text
    expected_version: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NewEvent]: ...
    require_leader: builtins.bool
    def __init__(self,
        *,
        event_stream_id: typing.Optional[typing.Text] = ...,
        expected_version: typing.Optional[builtins.int] = ...,
        events: typing.Optional[typing.Iterable[global___NewEvent]] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","expected_version",b"expected_version","require_leader",b"require_leader"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","events",b"events","expected_version",b"expected_version","require_leader",b"require_leader"]) -> None: ...
global___WriteEvents = WriteEvents

class WriteEventsCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    FIRST_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    LAST_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    CURRENT_VERSION_FIELD_NUMBER: builtins.int
    result: global___OperationResult.ValueType
    message: typing.Text
    first_event_number: builtins.int
    last_event_number: builtins.int
    prepare_position: builtins.int
    commit_position: builtins.int
    current_version: builtins.int
    def __init__(self,
        *,
        result: typing.Optional[global___OperationResult.ValueType] = ...,
        message: typing.Optional[typing.Text] = ...,
        first_event_number: typing.Optional[builtins.int] = ...,
        last_event_number: typing.Optional[builtins.int] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        commit_position: typing.Optional[builtins.int] = ...,
        current_version: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","current_version",b"current_version","first_event_number",b"first_event_number","last_event_number",b"last_event_number","message",b"message","prepare_position",b"prepare_position","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","current_version",b"current_version","first_event_number",b"first_event_number","last_event_number",b"last_event_number","message",b"message","prepare_position",b"prepare_position","result",b"result"]) -> None: ...
global___WriteEventsCompleted = WriteEventsCompleted

class DeleteStream(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    EXPECTED_VERSION_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    HARD_DELETE_FIELD_NUMBER: builtins.int
    event_stream_id: typing.Text
    expected_version: builtins.int
    require_leader: builtins.bool
    hard_delete: builtins.bool
    def __init__(self,
        *,
        event_stream_id: typing.Optional[typing.Text] = ...,
        expected_version: typing.Optional[builtins.int] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        hard_delete: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","expected_version",b"expected_version","hard_delete",b"hard_delete","require_leader",b"require_leader"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","expected_version",b"expected_version","hard_delete",b"hard_delete","require_leader",b"require_leader"]) -> None: ...
global___DeleteStream = DeleteStream

class DeleteStreamCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    result: global___OperationResult.ValueType
    message: typing.Text
    prepare_position: builtins.int
    commit_position: builtins.int
    def __init__(self,
        *,
        result: typing.Optional[global___OperationResult.ValueType] = ...,
        message: typing.Optional[typing.Text] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        commit_position: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","message",b"message","prepare_position",b"prepare_position","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","message",b"message","prepare_position",b"prepare_position","result",b"result"]) -> None: ...
global___DeleteStreamCompleted = DeleteStreamCompleted

class TransactionStart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    EXPECTED_VERSION_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    event_stream_id: typing.Text
    expected_version: builtins.int
    require_leader: builtins.bool
    def __init__(self,
        *,
        event_stream_id: typing.Optional[typing.Text] = ...,
        expected_version: typing.Optional[builtins.int] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","expected_version",b"expected_version","require_leader",b"require_leader"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","expected_version",b"expected_version","require_leader",b"require_leader"]) -> None: ...
global___TransactionStart = TransactionStart

class TransactionStartCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRANSACTION_ID_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    transaction_id: builtins.int
    result: global___OperationResult.ValueType
    message: typing.Text
    def __init__(self,
        *,
        transaction_id: typing.Optional[builtins.int] = ...,
        result: typing.Optional[global___OperationResult.ValueType] = ...,
        message: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message",b"message","result",b"result","transaction_id",b"transaction_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message","result",b"result","transaction_id",b"transaction_id"]) -> None: ...
global___TransactionStartCompleted = TransactionStartCompleted

class TransactionWrite(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRANSACTION_ID_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    transaction_id: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NewEvent]: ...
    require_leader: builtins.bool
    def __init__(self,
        *,
        transaction_id: typing.Optional[builtins.int] = ...,
        events: typing.Optional[typing.Iterable[global___NewEvent]] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["require_leader",b"require_leader","transaction_id",b"transaction_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["events",b"events","require_leader",b"require_leader","transaction_id",b"transaction_id"]) -> None: ...
global___TransactionWrite = TransactionWrite

class TransactionWriteCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRANSACTION_ID_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    transaction_id: builtins.int
    result: global___OperationResult.ValueType
    message: typing.Text
    def __init__(self,
        *,
        transaction_id: typing.Optional[builtins.int] = ...,
        result: typing.Optional[global___OperationResult.ValueType] = ...,
        message: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message",b"message","result",b"result","transaction_id",b"transaction_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message","result",b"result","transaction_id",b"transaction_id"]) -> None: ...
global___TransactionWriteCompleted = TransactionWriteCompleted

class TransactionCommit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRANSACTION_ID_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    transaction_id: builtins.int
    require_leader: builtins.bool
    def __init__(self,
        *,
        transaction_id: typing.Optional[builtins.int] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["require_leader",b"require_leader","transaction_id",b"transaction_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["require_leader",b"require_leader","transaction_id",b"transaction_id"]) -> None: ...
global___TransactionCommit = TransactionCommit

class TransactionCommitCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRANSACTION_ID_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    FIRST_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    LAST_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    transaction_id: builtins.int
    result: global___OperationResult.ValueType
    message: typing.Text
    first_event_number: builtins.int
    last_event_number: builtins.int
    prepare_position: builtins.int
    commit_position: builtins.int
    def __init__(self,
        *,
        transaction_id: typing.Optional[builtins.int] = ...,
        result: typing.Optional[global___OperationResult.ValueType] = ...,
        message: typing.Optional[typing.Text] = ...,
        first_event_number: typing.Optional[builtins.int] = ...,
        last_event_number: typing.Optional[builtins.int] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        commit_position: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","first_event_number",b"first_event_number","last_event_number",b"last_event_number","message",b"message","prepare_position",b"prepare_position","result",b"result","transaction_id",b"transaction_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","first_event_number",b"first_event_number","last_event_number",b"last_event_number","message",b"message","prepare_position",b"prepare_position","result",b"result","transaction_id",b"transaction_id"]) -> None: ...
global___TransactionCommitCompleted = TransactionCommitCompleted

class ReadEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    EVENT_NUMBER_FIELD_NUMBER: builtins.int
    RESOLVE_LINK_TOS_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    event_stream_id: typing.Text
    event_number: builtins.int
    resolve_link_tos: builtins.bool
    require_leader: builtins.bool
    def __init__(self,
        *,
        event_stream_id: typing.Optional[typing.Text] = ...,
        event_number: typing.Optional[builtins.int] = ...,
        resolve_link_tos: typing.Optional[builtins.bool] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_number",b"event_number","event_stream_id",b"event_stream_id","require_leader",b"require_leader","resolve_link_tos",b"resolve_link_tos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_number",b"event_number","event_stream_id",b"event_stream_id","require_leader",b"require_leader","resolve_link_tos",b"resolve_link_tos"]) -> None: ...
global___ReadEvent = ReadEvent

class ReadEventCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ReadEventResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ReadEventResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ReadEventCompleted._ReadEventResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Success: ReadEventCompleted._ReadEventResult.ValueType  # 0
        NotFound: ReadEventCompleted._ReadEventResult.ValueType  # 1
        NoStream: ReadEventCompleted._ReadEventResult.ValueType  # 2
        StreamDeleted: ReadEventCompleted._ReadEventResult.ValueType  # 3
        Error: ReadEventCompleted._ReadEventResult.ValueType  # 4
        AccessDenied: ReadEventCompleted._ReadEventResult.ValueType  # 5
    class ReadEventResult(_ReadEventResult, metaclass=_ReadEventResultEnumTypeWrapper):
        pass

    Success: ReadEventCompleted.ReadEventResult.ValueType  # 0
    NotFound: ReadEventCompleted.ReadEventResult.ValueType  # 1
    NoStream: ReadEventCompleted.ReadEventResult.ValueType  # 2
    StreamDeleted: ReadEventCompleted.ReadEventResult.ValueType  # 3
    Error: ReadEventCompleted.ReadEventResult.ValueType  # 4
    AccessDenied: ReadEventCompleted.ReadEventResult.ValueType  # 5

    RESULT_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    result: global___ReadEventCompleted.ReadEventResult.ValueType
    @property
    def event(self) -> global___ResolvedIndexedEvent: ...
    error: typing.Text
    def __init__(self,
        *,
        result: typing.Optional[global___ReadEventCompleted.ReadEventResult.ValueType] = ...,
        event: typing.Optional[global___ResolvedIndexedEvent] = ...,
        error: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error",b"error","event",b"event","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error",b"error","event",b"event","result",b"result"]) -> None: ...
global___ReadEventCompleted = ReadEventCompleted

class ReadStreamEvents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    FROM_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    MAX_COUNT_FIELD_NUMBER: builtins.int
    RESOLVE_LINK_TOS_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    event_stream_id: typing.Text
    from_event_number: builtins.int
    max_count: builtins.int
    resolve_link_tos: builtins.bool
    require_leader: builtins.bool
    def __init__(self,
        *,
        event_stream_id: typing.Optional[typing.Text] = ...,
        from_event_number: typing.Optional[builtins.int] = ...,
        max_count: typing.Optional[builtins.int] = ...,
        resolve_link_tos: typing.Optional[builtins.bool] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","from_event_number",b"from_event_number","max_count",b"max_count","require_leader",b"require_leader","resolve_link_tos",b"resolve_link_tos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","from_event_number",b"from_event_number","max_count",b"max_count","require_leader",b"require_leader","resolve_link_tos",b"resolve_link_tos"]) -> None: ...
global___ReadStreamEvents = ReadStreamEvents

class ReadStreamEventsCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ReadStreamResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ReadStreamResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ReadStreamEventsCompleted._ReadStreamResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Success: ReadStreamEventsCompleted._ReadStreamResult.ValueType  # 0
        NoStream: ReadStreamEventsCompleted._ReadStreamResult.ValueType  # 1
        StreamDeleted: ReadStreamEventsCompleted._ReadStreamResult.ValueType  # 2
        NotModified: ReadStreamEventsCompleted._ReadStreamResult.ValueType  # 3
        Error: ReadStreamEventsCompleted._ReadStreamResult.ValueType  # 4
        AccessDenied: ReadStreamEventsCompleted._ReadStreamResult.ValueType  # 5
    class ReadStreamResult(_ReadStreamResult, metaclass=_ReadStreamResultEnumTypeWrapper):
        pass

    Success: ReadStreamEventsCompleted.ReadStreamResult.ValueType  # 0
    NoStream: ReadStreamEventsCompleted.ReadStreamResult.ValueType  # 1
    StreamDeleted: ReadStreamEventsCompleted.ReadStreamResult.ValueType  # 2
    NotModified: ReadStreamEventsCompleted.ReadStreamResult.ValueType  # 3
    Error: ReadStreamEventsCompleted.ReadStreamResult.ValueType  # 4
    AccessDenied: ReadStreamEventsCompleted.ReadStreamResult.ValueType  # 5

    EVENTS_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    NEXT_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    LAST_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    IS_END_OF_STREAM_FIELD_NUMBER: builtins.int
    LAST_COMMIT_POSITION_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResolvedIndexedEvent]: ...
    result: global___ReadStreamEventsCompleted.ReadStreamResult.ValueType
    next_event_number: builtins.int
    last_event_number: builtins.int
    is_end_of_stream: builtins.bool
    last_commit_position: builtins.int
    error: typing.Text
    def __init__(self,
        *,
        events: typing.Optional[typing.Iterable[global___ResolvedIndexedEvent]] = ...,
        result: typing.Optional[global___ReadStreamEventsCompleted.ReadStreamResult.ValueType] = ...,
        next_event_number: typing.Optional[builtins.int] = ...,
        last_event_number: typing.Optional[builtins.int] = ...,
        is_end_of_stream: typing.Optional[builtins.bool] = ...,
        last_commit_position: typing.Optional[builtins.int] = ...,
        error: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error",b"error","is_end_of_stream",b"is_end_of_stream","last_commit_position",b"last_commit_position","last_event_number",b"last_event_number","next_event_number",b"next_event_number","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error",b"error","events",b"events","is_end_of_stream",b"is_end_of_stream","last_commit_position",b"last_commit_position","last_event_number",b"last_event_number","next_event_number",b"next_event_number","result",b"result"]) -> None: ...
global___ReadStreamEventsCompleted = ReadStreamEventsCompleted

class ReadAllEvents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    MAX_COUNT_FIELD_NUMBER: builtins.int
    RESOLVE_LINK_TOS_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    commit_position: builtins.int
    prepare_position: builtins.int
    max_count: builtins.int
    resolve_link_tos: builtins.bool
    require_leader: builtins.bool
    def __init__(self,
        *,
        commit_position: typing.Optional[builtins.int] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        max_count: typing.Optional[builtins.int] = ...,
        resolve_link_tos: typing.Optional[builtins.bool] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","max_count",b"max_count","prepare_position",b"prepare_position","require_leader",b"require_leader","resolve_link_tos",b"resolve_link_tos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","max_count",b"max_count","prepare_position",b"prepare_position","require_leader",b"require_leader","resolve_link_tos",b"resolve_link_tos"]) -> None: ...
global___ReadAllEvents = ReadAllEvents

class ReadAllEventsCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ReadAllResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ReadAllResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ReadAllEventsCompleted._ReadAllResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Success: ReadAllEventsCompleted._ReadAllResult.ValueType  # 0
        NotModified: ReadAllEventsCompleted._ReadAllResult.ValueType  # 1
        Error: ReadAllEventsCompleted._ReadAllResult.ValueType  # 2
        AccessDenied: ReadAllEventsCompleted._ReadAllResult.ValueType  # 3
    class ReadAllResult(_ReadAllResult, metaclass=_ReadAllResultEnumTypeWrapper):
        pass

    Success: ReadAllEventsCompleted.ReadAllResult.ValueType  # 0
    NotModified: ReadAllEventsCompleted.ReadAllResult.ValueType  # 1
    Error: ReadAllEventsCompleted.ReadAllResult.ValueType  # 2
    AccessDenied: ReadAllEventsCompleted.ReadAllResult.ValueType  # 3

    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    NEXT_COMMIT_POSITION_FIELD_NUMBER: builtins.int
    NEXT_PREPARE_POSITION_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    commit_position: builtins.int
    prepare_position: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResolvedEvent]: ...
    next_commit_position: builtins.int
    next_prepare_position: builtins.int
    result: global___ReadAllEventsCompleted.ReadAllResult.ValueType
    error: typing.Text
    def __init__(self,
        *,
        commit_position: typing.Optional[builtins.int] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        events: typing.Optional[typing.Iterable[global___ResolvedEvent]] = ...,
        next_commit_position: typing.Optional[builtins.int] = ...,
        next_prepare_position: typing.Optional[builtins.int] = ...,
        result: typing.Optional[global___ReadAllEventsCompleted.ReadAllResult.ValueType] = ...,
        error: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","error",b"error","next_commit_position",b"next_commit_position","next_prepare_position",b"next_prepare_position","prepare_position",b"prepare_position","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","error",b"error","events",b"events","next_commit_position",b"next_commit_position","next_prepare_position",b"next_prepare_position","prepare_position",b"prepare_position","result",b"result"]) -> None: ...
global___ReadAllEventsCompleted = ReadAllEventsCompleted

class Filter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _FilterContext:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _FilterContextEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Filter._FilterContext.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        StreamId: Filter._FilterContext.ValueType  # 0
        EventType: Filter._FilterContext.ValueType  # 1
    class FilterContext(_FilterContext, metaclass=_FilterContextEnumTypeWrapper):
        pass

    StreamId: Filter.FilterContext.ValueType  # 0
    EventType: Filter.FilterContext.ValueType  # 1

    class _FilterType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _FilterTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Filter._FilterType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Regex: Filter._FilterType.ValueType  # 0
        Prefix: Filter._FilterType.ValueType  # 1
    class FilterType(_FilterType, metaclass=_FilterTypeEnumTypeWrapper):
        pass

    Regex: Filter.FilterType.ValueType  # 0
    Prefix: Filter.FilterType.ValueType  # 1

    CONTEXT_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    context: global___Filter.FilterContext.ValueType
    type: global___Filter.FilterType.ValueType
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        context: typing.Optional[global___Filter.FilterContext.ValueType] = ...,
        type: typing.Optional[global___Filter.FilterType.ValueType] = ...,
        data: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["context",b"context","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["context",b"context","data",b"data","type",b"type"]) -> None: ...
global___Filter = Filter

class FilteredReadAllEvents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    MAX_COUNT_FIELD_NUMBER: builtins.int
    MAX_SEARCH_WINDOW_FIELD_NUMBER: builtins.int
    RESOLVE_LINK_TOS_FIELD_NUMBER: builtins.int
    REQUIRE_LEADER_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    commit_position: builtins.int
    prepare_position: builtins.int
    max_count: builtins.int
    max_search_window: builtins.int
    resolve_link_tos: builtins.bool
    require_leader: builtins.bool
    @property
    def filter(self) -> global___Filter: ...
    def __init__(self,
        *,
        commit_position: typing.Optional[builtins.int] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        max_count: typing.Optional[builtins.int] = ...,
        max_search_window: typing.Optional[builtins.int] = ...,
        resolve_link_tos: typing.Optional[builtins.bool] = ...,
        require_leader: typing.Optional[builtins.bool] = ...,
        filter: typing.Optional[global___Filter] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","filter",b"filter","max_count",b"max_count","max_search_window",b"max_search_window","prepare_position",b"prepare_position","require_leader",b"require_leader","resolve_link_tos",b"resolve_link_tos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","filter",b"filter","max_count",b"max_count","max_search_window",b"max_search_window","prepare_position",b"prepare_position","require_leader",b"require_leader","resolve_link_tos",b"resolve_link_tos"]) -> None: ...
global___FilteredReadAllEvents = FilteredReadAllEvents

class FilteredReadAllEventsCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _FilteredReadAllResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _FilteredReadAllResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[FilteredReadAllEventsCompleted._FilteredReadAllResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Success: FilteredReadAllEventsCompleted._FilteredReadAllResult.ValueType  # 0
        NotModified: FilteredReadAllEventsCompleted._FilteredReadAllResult.ValueType  # 1
        Error: FilteredReadAllEventsCompleted._FilteredReadAllResult.ValueType  # 2
        AccessDenied: FilteredReadAllEventsCompleted._FilteredReadAllResult.ValueType  # 3
    class FilteredReadAllResult(_FilteredReadAllResult, metaclass=_FilteredReadAllResultEnumTypeWrapper):
        pass

    Success: FilteredReadAllEventsCompleted.FilteredReadAllResult.ValueType  # 0
    NotModified: FilteredReadAllEventsCompleted.FilteredReadAllResult.ValueType  # 1
    Error: FilteredReadAllEventsCompleted.FilteredReadAllResult.ValueType  # 2
    AccessDenied: FilteredReadAllEventsCompleted.FilteredReadAllResult.ValueType  # 3

    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    NEXT_COMMIT_POSITION_FIELD_NUMBER: builtins.int
    NEXT_PREPARE_POSITION_FIELD_NUMBER: builtins.int
    IS_END_OF_STREAM_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    commit_position: builtins.int
    prepare_position: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResolvedEvent]: ...
    next_commit_position: builtins.int
    next_prepare_position: builtins.int
    is_end_of_stream: builtins.bool
    result: global___FilteredReadAllEventsCompleted.FilteredReadAllResult.ValueType
    error: typing.Text
    def __init__(self,
        *,
        commit_position: typing.Optional[builtins.int] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        events: typing.Optional[typing.Iterable[global___ResolvedEvent]] = ...,
        next_commit_position: typing.Optional[builtins.int] = ...,
        next_prepare_position: typing.Optional[builtins.int] = ...,
        is_end_of_stream: typing.Optional[builtins.bool] = ...,
        result: typing.Optional[global___FilteredReadAllEventsCompleted.FilteredReadAllResult.ValueType] = ...,
        error: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","error",b"error","is_end_of_stream",b"is_end_of_stream","next_commit_position",b"next_commit_position","next_prepare_position",b"next_prepare_position","prepare_position",b"prepare_position","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","error",b"error","events",b"events","is_end_of_stream",b"is_end_of_stream","next_commit_position",b"next_commit_position","next_prepare_position",b"next_prepare_position","prepare_position",b"prepare_position","result",b"result"]) -> None: ...
global___FilteredReadAllEventsCompleted = FilteredReadAllEventsCompleted

class CreatePersistentSubscription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBSCRIPTION_GROUP_NAME_FIELD_NUMBER: builtins.int
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    RESOLVE_LINK_TOS_FIELD_NUMBER: builtins.int
    START_FROM_FIELD_NUMBER: builtins.int
    MESSAGE_TIMEOUT_MILLISECONDS_FIELD_NUMBER: builtins.int
    RECORD_STATISTICS_FIELD_NUMBER: builtins.int
    LIVE_BUFFER_SIZE_FIELD_NUMBER: builtins.int
    READ_BATCH_SIZE_FIELD_NUMBER: builtins.int
    BUFFER_SIZE_FIELD_NUMBER: builtins.int
    MAX_RETRY_COUNT_FIELD_NUMBER: builtins.int
    PREFER_ROUND_ROBIN_FIELD_NUMBER: builtins.int
    CHECKPOINT_AFTER_TIME_FIELD_NUMBER: builtins.int
    CHECKPOINT_MAX_COUNT_FIELD_NUMBER: builtins.int
    CHECKPOINT_MIN_COUNT_FIELD_NUMBER: builtins.int
    SUBSCRIBER_MAX_COUNT_FIELD_NUMBER: builtins.int
    NAMED_CONSUMER_STRATEGY_FIELD_NUMBER: builtins.int
    subscription_group_name: typing.Text
    event_stream_id: typing.Text
    resolve_link_tos: builtins.bool
    start_from: builtins.int
    message_timeout_milliseconds: builtins.int
    record_statistics: builtins.bool
    live_buffer_size: builtins.int
    read_batch_size: builtins.int
    buffer_size: builtins.int
    max_retry_count: builtins.int
    prefer_round_robin: builtins.bool
    checkpoint_after_time: builtins.int
    checkpoint_max_count: builtins.int
    checkpoint_min_count: builtins.int
    subscriber_max_count: builtins.int
    named_consumer_strategy: typing.Text
    def __init__(self,
        *,
        subscription_group_name: typing.Optional[typing.Text] = ...,
        event_stream_id: typing.Optional[typing.Text] = ...,
        resolve_link_tos: typing.Optional[builtins.bool] = ...,
        start_from: typing.Optional[builtins.int] = ...,
        message_timeout_milliseconds: typing.Optional[builtins.int] = ...,
        record_statistics: typing.Optional[builtins.bool] = ...,
        live_buffer_size: typing.Optional[builtins.int] = ...,
        read_batch_size: typing.Optional[builtins.int] = ...,
        buffer_size: typing.Optional[builtins.int] = ...,
        max_retry_count: typing.Optional[builtins.int] = ...,
        prefer_round_robin: typing.Optional[builtins.bool] = ...,
        checkpoint_after_time: typing.Optional[builtins.int] = ...,
        checkpoint_max_count: typing.Optional[builtins.int] = ...,
        checkpoint_min_count: typing.Optional[builtins.int] = ...,
        subscriber_max_count: typing.Optional[builtins.int] = ...,
        named_consumer_strategy: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["buffer_size",b"buffer_size","checkpoint_after_time",b"checkpoint_after_time","checkpoint_max_count",b"checkpoint_max_count","checkpoint_min_count",b"checkpoint_min_count","event_stream_id",b"event_stream_id","live_buffer_size",b"live_buffer_size","max_retry_count",b"max_retry_count","message_timeout_milliseconds",b"message_timeout_milliseconds","named_consumer_strategy",b"named_consumer_strategy","prefer_round_robin",b"prefer_round_robin","read_batch_size",b"read_batch_size","record_statistics",b"record_statistics","resolve_link_tos",b"resolve_link_tos","start_from",b"start_from","subscriber_max_count",b"subscriber_max_count","subscription_group_name",b"subscription_group_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["buffer_size",b"buffer_size","checkpoint_after_time",b"checkpoint_after_time","checkpoint_max_count",b"checkpoint_max_count","checkpoint_min_count",b"checkpoint_min_count","event_stream_id",b"event_stream_id","live_buffer_size",b"live_buffer_size","max_retry_count",b"max_retry_count","message_timeout_milliseconds",b"message_timeout_milliseconds","named_consumer_strategy",b"named_consumer_strategy","prefer_round_robin",b"prefer_round_robin","read_batch_size",b"read_batch_size","record_statistics",b"record_statistics","resolve_link_tos",b"resolve_link_tos","start_from",b"start_from","subscriber_max_count",b"subscriber_max_count","subscription_group_name",b"subscription_group_name"]) -> None: ...
global___CreatePersistentSubscription = CreatePersistentSubscription

class DeletePersistentSubscription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBSCRIPTION_GROUP_NAME_FIELD_NUMBER: builtins.int
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    subscription_group_name: typing.Text
    event_stream_id: typing.Text
    def __init__(self,
        *,
        subscription_group_name: typing.Optional[typing.Text] = ...,
        event_stream_id: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","subscription_group_name",b"subscription_group_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","subscription_group_name",b"subscription_group_name"]) -> None: ...
global___DeletePersistentSubscription = DeletePersistentSubscription

class UpdatePersistentSubscription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBSCRIPTION_GROUP_NAME_FIELD_NUMBER: builtins.int
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    RESOLVE_LINK_TOS_FIELD_NUMBER: builtins.int
    START_FROM_FIELD_NUMBER: builtins.int
    MESSAGE_TIMEOUT_MILLISECONDS_FIELD_NUMBER: builtins.int
    RECORD_STATISTICS_FIELD_NUMBER: builtins.int
    LIVE_BUFFER_SIZE_FIELD_NUMBER: builtins.int
    READ_BATCH_SIZE_FIELD_NUMBER: builtins.int
    BUFFER_SIZE_FIELD_NUMBER: builtins.int
    MAX_RETRY_COUNT_FIELD_NUMBER: builtins.int
    PREFER_ROUND_ROBIN_FIELD_NUMBER: builtins.int
    CHECKPOINT_AFTER_TIME_FIELD_NUMBER: builtins.int
    CHECKPOINT_MAX_COUNT_FIELD_NUMBER: builtins.int
    CHECKPOINT_MIN_COUNT_FIELD_NUMBER: builtins.int
    SUBSCRIBER_MAX_COUNT_FIELD_NUMBER: builtins.int
    NAMED_CONSUMER_STRATEGY_FIELD_NUMBER: builtins.int
    subscription_group_name: typing.Text
    event_stream_id: typing.Text
    resolve_link_tos: builtins.bool
    start_from: builtins.int
    message_timeout_milliseconds: builtins.int
    record_statistics: builtins.bool
    live_buffer_size: builtins.int
    read_batch_size: builtins.int
    buffer_size: builtins.int
    max_retry_count: builtins.int
    prefer_round_robin: builtins.bool
    checkpoint_after_time: builtins.int
    checkpoint_max_count: builtins.int
    checkpoint_min_count: builtins.int
    subscriber_max_count: builtins.int
    named_consumer_strategy: typing.Text
    def __init__(self,
        *,
        subscription_group_name: typing.Optional[typing.Text] = ...,
        event_stream_id: typing.Optional[typing.Text] = ...,
        resolve_link_tos: typing.Optional[builtins.bool] = ...,
        start_from: typing.Optional[builtins.int] = ...,
        message_timeout_milliseconds: typing.Optional[builtins.int] = ...,
        record_statistics: typing.Optional[builtins.bool] = ...,
        live_buffer_size: typing.Optional[builtins.int] = ...,
        read_batch_size: typing.Optional[builtins.int] = ...,
        buffer_size: typing.Optional[builtins.int] = ...,
        max_retry_count: typing.Optional[builtins.int] = ...,
        prefer_round_robin: typing.Optional[builtins.bool] = ...,
        checkpoint_after_time: typing.Optional[builtins.int] = ...,
        checkpoint_max_count: typing.Optional[builtins.int] = ...,
        checkpoint_min_count: typing.Optional[builtins.int] = ...,
        subscriber_max_count: typing.Optional[builtins.int] = ...,
        named_consumer_strategy: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["buffer_size",b"buffer_size","checkpoint_after_time",b"checkpoint_after_time","checkpoint_max_count",b"checkpoint_max_count","checkpoint_min_count",b"checkpoint_min_count","event_stream_id",b"event_stream_id","live_buffer_size",b"live_buffer_size","max_retry_count",b"max_retry_count","message_timeout_milliseconds",b"message_timeout_milliseconds","named_consumer_strategy",b"named_consumer_strategy","prefer_round_robin",b"prefer_round_robin","read_batch_size",b"read_batch_size","record_statistics",b"record_statistics","resolve_link_tos",b"resolve_link_tos","start_from",b"start_from","subscriber_max_count",b"subscriber_max_count","subscription_group_name",b"subscription_group_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["buffer_size",b"buffer_size","checkpoint_after_time",b"checkpoint_after_time","checkpoint_max_count",b"checkpoint_max_count","checkpoint_min_count",b"checkpoint_min_count","event_stream_id",b"event_stream_id","live_buffer_size",b"live_buffer_size","max_retry_count",b"max_retry_count","message_timeout_milliseconds",b"message_timeout_milliseconds","named_consumer_strategy",b"named_consumer_strategy","prefer_round_robin",b"prefer_round_robin","read_batch_size",b"read_batch_size","record_statistics",b"record_statistics","resolve_link_tos",b"resolve_link_tos","start_from",b"start_from","subscriber_max_count",b"subscriber_max_count","subscription_group_name",b"subscription_group_name"]) -> None: ...
global___UpdatePersistentSubscription = UpdatePersistentSubscription

class UpdatePersistentSubscriptionCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _UpdatePersistentSubscriptionResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _UpdatePersistentSubscriptionResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UpdatePersistentSubscriptionCompleted._UpdatePersistentSubscriptionResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Success: UpdatePersistentSubscriptionCompleted._UpdatePersistentSubscriptionResult.ValueType  # 0
        DoesNotExist: UpdatePersistentSubscriptionCompleted._UpdatePersistentSubscriptionResult.ValueType  # 1
        Fail: UpdatePersistentSubscriptionCompleted._UpdatePersistentSubscriptionResult.ValueType  # 2
        AccessDenied: UpdatePersistentSubscriptionCompleted._UpdatePersistentSubscriptionResult.ValueType  # 3
    class UpdatePersistentSubscriptionResult(_UpdatePersistentSubscriptionResult, metaclass=_UpdatePersistentSubscriptionResultEnumTypeWrapper):
        pass

    Success: UpdatePersistentSubscriptionCompleted.UpdatePersistentSubscriptionResult.ValueType  # 0
    DoesNotExist: UpdatePersistentSubscriptionCompleted.UpdatePersistentSubscriptionResult.ValueType  # 1
    Fail: UpdatePersistentSubscriptionCompleted.UpdatePersistentSubscriptionResult.ValueType  # 2
    AccessDenied: UpdatePersistentSubscriptionCompleted.UpdatePersistentSubscriptionResult.ValueType  # 3

    RESULT_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    result: global___UpdatePersistentSubscriptionCompleted.UpdatePersistentSubscriptionResult.ValueType
    reason: typing.Text
    def __init__(self,
        *,
        result: typing.Optional[global___UpdatePersistentSubscriptionCompleted.UpdatePersistentSubscriptionResult.ValueType] = ...,
        reason: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reason",b"reason","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["reason",b"reason","result",b"result"]) -> None: ...
global___UpdatePersistentSubscriptionCompleted = UpdatePersistentSubscriptionCompleted

class CreatePersistentSubscriptionCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _CreatePersistentSubscriptionResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _CreatePersistentSubscriptionResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CreatePersistentSubscriptionCompleted._CreatePersistentSubscriptionResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Success: CreatePersistentSubscriptionCompleted._CreatePersistentSubscriptionResult.ValueType  # 0
        AlreadyExists: CreatePersistentSubscriptionCompleted._CreatePersistentSubscriptionResult.ValueType  # 1
        Fail: CreatePersistentSubscriptionCompleted._CreatePersistentSubscriptionResult.ValueType  # 2
        AccessDenied: CreatePersistentSubscriptionCompleted._CreatePersistentSubscriptionResult.ValueType  # 3
    class CreatePersistentSubscriptionResult(_CreatePersistentSubscriptionResult, metaclass=_CreatePersistentSubscriptionResultEnumTypeWrapper):
        pass

    Success: CreatePersistentSubscriptionCompleted.CreatePersistentSubscriptionResult.ValueType  # 0
    AlreadyExists: CreatePersistentSubscriptionCompleted.CreatePersistentSubscriptionResult.ValueType  # 1
    Fail: CreatePersistentSubscriptionCompleted.CreatePersistentSubscriptionResult.ValueType  # 2
    AccessDenied: CreatePersistentSubscriptionCompleted.CreatePersistentSubscriptionResult.ValueType  # 3

    RESULT_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    result: global___CreatePersistentSubscriptionCompleted.CreatePersistentSubscriptionResult.ValueType
    reason: typing.Text
    def __init__(self,
        *,
        result: typing.Optional[global___CreatePersistentSubscriptionCompleted.CreatePersistentSubscriptionResult.ValueType] = ...,
        reason: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reason",b"reason","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["reason",b"reason","result",b"result"]) -> None: ...
global___CreatePersistentSubscriptionCompleted = CreatePersistentSubscriptionCompleted

class DeletePersistentSubscriptionCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _DeletePersistentSubscriptionResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _DeletePersistentSubscriptionResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DeletePersistentSubscriptionCompleted._DeletePersistentSubscriptionResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Success: DeletePersistentSubscriptionCompleted._DeletePersistentSubscriptionResult.ValueType  # 0
        DoesNotExist: DeletePersistentSubscriptionCompleted._DeletePersistentSubscriptionResult.ValueType  # 1
        Fail: DeletePersistentSubscriptionCompleted._DeletePersistentSubscriptionResult.ValueType  # 2
        AccessDenied: DeletePersistentSubscriptionCompleted._DeletePersistentSubscriptionResult.ValueType  # 3
    class DeletePersistentSubscriptionResult(_DeletePersistentSubscriptionResult, metaclass=_DeletePersistentSubscriptionResultEnumTypeWrapper):
        pass

    Success: DeletePersistentSubscriptionCompleted.DeletePersistentSubscriptionResult.ValueType  # 0
    DoesNotExist: DeletePersistentSubscriptionCompleted.DeletePersistentSubscriptionResult.ValueType  # 1
    Fail: DeletePersistentSubscriptionCompleted.DeletePersistentSubscriptionResult.ValueType  # 2
    AccessDenied: DeletePersistentSubscriptionCompleted.DeletePersistentSubscriptionResult.ValueType  # 3

    RESULT_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    result: global___DeletePersistentSubscriptionCompleted.DeletePersistentSubscriptionResult.ValueType
    reason: typing.Text
    def __init__(self,
        *,
        result: typing.Optional[global___DeletePersistentSubscriptionCompleted.DeletePersistentSubscriptionResult.ValueType] = ...,
        reason: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reason",b"reason","result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["reason",b"reason","result",b"result"]) -> None: ...
global___DeletePersistentSubscriptionCompleted = DeletePersistentSubscriptionCompleted

class ConnectToPersistentSubscription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBSCRIPTION_ID_FIELD_NUMBER: builtins.int
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    ALLOWED_IN_FLIGHT_MESSAGES_FIELD_NUMBER: builtins.int
    subscription_id: typing.Text
    event_stream_id: typing.Text
    allowed_in_flight_messages: builtins.int
    def __init__(self,
        *,
        subscription_id: typing.Optional[typing.Text] = ...,
        event_stream_id: typing.Optional[typing.Text] = ...,
        allowed_in_flight_messages: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["allowed_in_flight_messages",b"allowed_in_flight_messages","event_stream_id",b"event_stream_id","subscription_id",b"subscription_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["allowed_in_flight_messages",b"allowed_in_flight_messages","event_stream_id",b"event_stream_id","subscription_id",b"subscription_id"]) -> None: ...
global___ConnectToPersistentSubscription = ConnectToPersistentSubscription

class PersistentSubscriptionAckEvents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBSCRIPTION_ID_FIELD_NUMBER: builtins.int
    PROCESSED_EVENT_IDS_FIELD_NUMBER: builtins.int
    subscription_id: typing.Text
    @property
    def processed_event_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(self,
        *,
        subscription_id: typing.Optional[typing.Text] = ...,
        processed_event_ids: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["subscription_id",b"subscription_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["processed_event_ids",b"processed_event_ids","subscription_id",b"subscription_id"]) -> None: ...
global___PersistentSubscriptionAckEvents = PersistentSubscriptionAckEvents

class PersistentSubscriptionNakEvents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _NakAction:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _NakActionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PersistentSubscriptionNakEvents._NakAction.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Unknown: PersistentSubscriptionNakEvents._NakAction.ValueType  # 0
        Park: PersistentSubscriptionNakEvents._NakAction.ValueType  # 1
        Retry: PersistentSubscriptionNakEvents._NakAction.ValueType  # 2
        Skip: PersistentSubscriptionNakEvents._NakAction.ValueType  # 3
        Stop: PersistentSubscriptionNakEvents._NakAction.ValueType  # 4
    class NakAction(_NakAction, metaclass=_NakActionEnumTypeWrapper):
        pass

    Unknown: PersistentSubscriptionNakEvents.NakAction.ValueType  # 0
    Park: PersistentSubscriptionNakEvents.NakAction.ValueType  # 1
    Retry: PersistentSubscriptionNakEvents.NakAction.ValueType  # 2
    Skip: PersistentSubscriptionNakEvents.NakAction.ValueType  # 3
    Stop: PersistentSubscriptionNakEvents.NakAction.ValueType  # 4

    SUBSCRIPTION_ID_FIELD_NUMBER: builtins.int
    PROCESSED_EVENT_IDS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    subscription_id: typing.Text
    @property
    def processed_event_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    message: typing.Text
    action: global___PersistentSubscriptionNakEvents.NakAction.ValueType
    def __init__(self,
        *,
        subscription_id: typing.Optional[typing.Text] = ...,
        processed_event_ids: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        message: typing.Optional[typing.Text] = ...,
        action: typing.Optional[global___PersistentSubscriptionNakEvents.NakAction.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["action",b"action","message",b"message","subscription_id",b"subscription_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["action",b"action","message",b"message","processed_event_ids",b"processed_event_ids","subscription_id",b"subscription_id"]) -> None: ...
global___PersistentSubscriptionNakEvents = PersistentSubscriptionNakEvents

class PersistentSubscriptionConfirmation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LAST_COMMIT_POSITION_FIELD_NUMBER: builtins.int
    SUBSCRIPTION_ID_FIELD_NUMBER: builtins.int
    LAST_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    last_commit_position: builtins.int
    subscription_id: typing.Text
    last_event_number: builtins.int
    def __init__(self,
        *,
        last_commit_position: typing.Optional[builtins.int] = ...,
        subscription_id: typing.Optional[typing.Text] = ...,
        last_event_number: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["last_commit_position",b"last_commit_position","last_event_number",b"last_event_number","subscription_id",b"subscription_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["last_commit_position",b"last_commit_position","last_event_number",b"last_event_number","subscription_id",b"subscription_id"]) -> None: ...
global___PersistentSubscriptionConfirmation = PersistentSubscriptionConfirmation

class PersistentSubscriptionStreamEventAppeared(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_FIELD_NUMBER: builtins.int
    RETRYCOUNT_FIELD_NUMBER: builtins.int
    @property
    def event(self) -> global___ResolvedIndexedEvent: ...
    retryCount: builtins.int
    def __init__(self,
        *,
        event: typing.Optional[global___ResolvedIndexedEvent] = ...,
        retryCount: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event",b"event","retryCount",b"retryCount"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event",b"event","retryCount",b"retryCount"]) -> None: ...
global___PersistentSubscriptionStreamEventAppeared = PersistentSubscriptionStreamEventAppeared

class SubscribeToStream(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    RESOLVE_LINK_TOS_FIELD_NUMBER: builtins.int
    event_stream_id: typing.Text
    resolve_link_tos: builtins.bool
    def __init__(self,
        *,
        event_stream_id: typing.Optional[typing.Text] = ...,
        resolve_link_tos: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","resolve_link_tos",b"resolve_link_tos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_stream_id",b"event_stream_id","resolve_link_tos",b"resolve_link_tos"]) -> None: ...
global___SubscribeToStream = SubscribeToStream

class FilteredSubscribeToStream(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_STREAM_ID_FIELD_NUMBER: builtins.int
    RESOLVE_LINK_TOS_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    CHECKPOINT_INTERVAL_FIELD_NUMBER: builtins.int
    event_stream_id: typing.Text
    resolve_link_tos: builtins.bool
    @property
    def filter(self) -> global___Filter: ...
    checkpoint_interval: builtins.int
    def __init__(self,
        *,
        event_stream_id: typing.Optional[typing.Text] = ...,
        resolve_link_tos: typing.Optional[builtins.bool] = ...,
        filter: typing.Optional[global___Filter] = ...,
        checkpoint_interval: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["checkpoint_interval",b"checkpoint_interval","event_stream_id",b"event_stream_id","filter",b"filter","resolve_link_tos",b"resolve_link_tos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["checkpoint_interval",b"checkpoint_interval","event_stream_id",b"event_stream_id","filter",b"filter","resolve_link_tos",b"resolve_link_tos"]) -> None: ...
global___FilteredSubscribeToStream = FilteredSubscribeToStream

class CheckpointReached(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMIT_POSITION_FIELD_NUMBER: builtins.int
    PREPARE_POSITION_FIELD_NUMBER: builtins.int
    commit_position: builtins.int
    prepare_position: builtins.int
    def __init__(self,
        *,
        commit_position: typing.Optional[builtins.int] = ...,
        prepare_position: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","prepare_position",b"prepare_position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_position",b"commit_position","prepare_position",b"prepare_position"]) -> None: ...
global___CheckpointReached = CheckpointReached

class SubscriptionConfirmation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LAST_COMMIT_POSITION_FIELD_NUMBER: builtins.int
    LAST_EVENT_NUMBER_FIELD_NUMBER: builtins.int
    last_commit_position: builtins.int
    last_event_number: builtins.int
    def __init__(self,
        *,
        last_commit_position: typing.Optional[builtins.int] = ...,
        last_event_number: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["last_commit_position",b"last_commit_position","last_event_number",b"last_event_number"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["last_commit_position",b"last_commit_position","last_event_number",b"last_event_number"]) -> None: ...
global___SubscriptionConfirmation = SubscriptionConfirmation

class StreamEventAppeared(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EVENT_FIELD_NUMBER: builtins.int
    @property
    def event(self) -> global___ResolvedEvent: ...
    def __init__(self,
        *,
        event: typing.Optional[global___ResolvedEvent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event",b"event"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event",b"event"]) -> None: ...
global___StreamEventAppeared = StreamEventAppeared

class UnsubscribeFromStream(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___UnsubscribeFromStream = UnsubscribeFromStream

class SubscriptionDropped(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _SubscriptionDropReason:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _SubscriptionDropReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SubscriptionDropped._SubscriptionDropReason.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Unsubscribed: SubscriptionDropped._SubscriptionDropReason.ValueType  # 0
        AccessDenied: SubscriptionDropped._SubscriptionDropReason.ValueType  # 1
        NotFound: SubscriptionDropped._SubscriptionDropReason.ValueType  # 2
        PersistentSubscriptionDeleted: SubscriptionDropped._SubscriptionDropReason.ValueType  # 3
        SubscriberMaxCountReached: SubscriptionDropped._SubscriptionDropReason.ValueType  # 4
    class SubscriptionDropReason(_SubscriptionDropReason, metaclass=_SubscriptionDropReasonEnumTypeWrapper):
        pass

    Unsubscribed: SubscriptionDropped.SubscriptionDropReason.ValueType  # 0
    AccessDenied: SubscriptionDropped.SubscriptionDropReason.ValueType  # 1
    NotFound: SubscriptionDropped.SubscriptionDropReason.ValueType  # 2
    PersistentSubscriptionDeleted: SubscriptionDropped.SubscriptionDropReason.ValueType  # 3
    SubscriberMaxCountReached: SubscriptionDropped.SubscriptionDropReason.ValueType  # 4

    REASON_FIELD_NUMBER: builtins.int
    reason: global___SubscriptionDropped.SubscriptionDropReason.ValueType
    def __init__(self,
        *,
        reason: typing.Optional[global___SubscriptionDropped.SubscriptionDropReason.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reason",b"reason"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["reason",b"reason"]) -> None: ...
global___SubscriptionDropped = SubscriptionDropped

class NotHandled(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _NotHandledReason:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _NotHandledReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[NotHandled._NotHandledReason.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NotReady: NotHandled._NotHandledReason.ValueType  # 0
        TooBusy: NotHandled._NotHandledReason.ValueType  # 1
        NotLeader: NotHandled._NotHandledReason.ValueType  # 2
        IsReadOnly: NotHandled._NotHandledReason.ValueType  # 3
    class NotHandledReason(_NotHandledReason, metaclass=_NotHandledReasonEnumTypeWrapper):
        pass

    NotReady: NotHandled.NotHandledReason.ValueType  # 0
    TooBusy: NotHandled.NotHandledReason.ValueType  # 1
    NotLeader: NotHandled.NotHandledReason.ValueType  # 2
    IsReadOnly: NotHandled.NotHandledReason.ValueType  # 3

    class LeaderInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        EXTERNAL_TCP_ADDRESS_FIELD_NUMBER: builtins.int
        EXTERNAL_TCP_PORT_FIELD_NUMBER: builtins.int
        HTTP_ADDRESS_FIELD_NUMBER: builtins.int
        HTTP_PORT_FIELD_NUMBER: builtins.int
        EXTERNAL_SECURE_TCP_ADDRESS_FIELD_NUMBER: builtins.int
        EXTERNAL_SECURE_TCP_PORT_FIELD_NUMBER: builtins.int
        external_tcp_address: typing.Text
        external_tcp_port: builtins.int
        http_address: typing.Text
        http_port: builtins.int
        external_secure_tcp_address: typing.Text
        external_secure_tcp_port: builtins.int
        def __init__(self,
            *,
            external_tcp_address: typing.Optional[typing.Text] = ...,
            external_tcp_port: typing.Optional[builtins.int] = ...,
            http_address: typing.Optional[typing.Text] = ...,
            http_port: typing.Optional[builtins.int] = ...,
            external_secure_tcp_address: typing.Optional[typing.Text] = ...,
            external_secure_tcp_port: typing.Optional[builtins.int] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["external_secure_tcp_address",b"external_secure_tcp_address","external_secure_tcp_port",b"external_secure_tcp_port","external_tcp_address",b"external_tcp_address","external_tcp_port",b"external_tcp_port","http_address",b"http_address","http_port",b"http_port"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["external_secure_tcp_address",b"external_secure_tcp_address","external_secure_tcp_port",b"external_secure_tcp_port","external_tcp_address",b"external_tcp_address","external_tcp_port",b"external_tcp_port","http_address",b"http_address","http_port",b"http_port"]) -> None: ...

    REASON_FIELD_NUMBER: builtins.int
    ADDITIONAL_INFO_FIELD_NUMBER: builtins.int
    reason: global___NotHandled.NotHandledReason.ValueType
    additional_info: builtins.bytes
    def __init__(self,
        *,
        reason: typing.Optional[global___NotHandled.NotHandledReason.ValueType] = ...,
        additional_info: typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["additional_info",b"additional_info","reason",b"reason"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["additional_info",b"additional_info","reason",b"reason"]) -> None: ...
global___NotHandled = NotHandled

class ScavengeDatabase(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ScavengeDatabase = ScavengeDatabase

class ScavengeDatabaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ScavengeResult:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ScavengeResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ScavengeDatabaseResponse._ScavengeResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Started: ScavengeDatabaseResponse._ScavengeResult.ValueType  # 0
        InProgress: ScavengeDatabaseResponse._ScavengeResult.ValueType  # 1
        Unauthorized: ScavengeDatabaseResponse._ScavengeResult.ValueType  # 2
    class ScavengeResult(_ScavengeResult, metaclass=_ScavengeResultEnumTypeWrapper):
        pass

    Started: ScavengeDatabaseResponse.ScavengeResult.ValueType  # 0
    InProgress: ScavengeDatabaseResponse.ScavengeResult.ValueType  # 1
    Unauthorized: ScavengeDatabaseResponse.ScavengeResult.ValueType  # 2

    RESULT_FIELD_NUMBER: builtins.int
    SCAVENGEID_FIELD_NUMBER: builtins.int
    result: global___ScavengeDatabaseResponse.ScavengeResult.ValueType
    scavengeId: typing.Text
    def __init__(self,
        *,
        result: typing.Optional[global___ScavengeDatabaseResponse.ScavengeResult.ValueType] = ...,
        scavengeId: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["result",b"result","scavengeId",b"scavengeId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result","scavengeId",b"scavengeId"]) -> None: ...
global___ScavengeDatabaseResponse = ScavengeDatabaseResponse

class IdentifyClient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VERSION_FIELD_NUMBER: builtins.int
    CONNECTION_NAME_FIELD_NUMBER: builtins.int
    version: builtins.int
    connection_name: typing.Text
    def __init__(self,
        *,
        version: typing.Optional[builtins.int] = ...,
        connection_name: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["connection_name",b"connection_name","version",b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["connection_name",b"connection_name","version",b"version"]) -> None: ...
global___IdentifyClient = IdentifyClient

class ClientIdentified(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ClientIdentified = ClientIdentified
